### ISSUE TITLE
Програмата не се стартира

### ISSUE THREAD

**Issue by Dxrk7958** [dayofpay/VignetteBulgariaCheck#1]
Когато опитам да стартирам софтуера получавам грешка **"Could not load file or assembly or one of its dependencies"** , на какво се дължи това ?

**Comment by dayofpay** [comment]
Здравейте, бихте ли ми предоставили данните за цялата грешка, също така, за да функционира софтуера безпроблемно трябва да изтеглите последната налична версия, а именно 1.7. Също така се уверете, че всички файлове от директорията  /lib имат копие и във папката, където е локализиран .exe файла. Ще съдействам, ако след насоките, които ви предоставих все още изпитвате затруднения със стартирането на програмата.

**Comment by Dxrk7958** [comment]
Сега като преместих файловете от /lib във .exe папката всичко е точно, мерси.
